print("=+=+=+=+ Data Diri Mahasiswa =+=+=+=+")
nim = input("NIM:")
nama = input("Nama Lengkap:")
jurusan = input("Jurusan:")
alamat = input("alamat:")
umur = int(input("umur:"))
berat_badan = float(input("Berat badan:"))
tinggi_badan =float(input("tinggi badan:"))

print(" Hasil cetak data diatas adalah")
print("Nim : " +str(nim))
print("Nama : " +str(nama))
print("Jurusan :" +str(jurusan))
print("Alamat :" +str(alamat))
print("Umur :" +str (umur))
print("Berat_badan :" +str(berat_badan))
print("Tinggi_badan :" +str(tinggi_badan))
