print("**********************************")
print("*                                *")
print("*      WELCOME TO OUR APP        *")
print("*                                *")
print("**********************************")
print("\n")
print("We are glad to have you here!")
print("Enjoy exploring our features and services.")
print("If you need any help, feel free to ask.")
print("\n")
print("Have a great day!")
